# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picture_or_drawing = QtWidgets.QComboBox(self.centralwidget)
        self.picture_or_drawing.setGeometry(QtCore.QRect(80, 160, 221, 41))
        self.picture_or_drawing.setObjectName("picture_or_drawing")
        self.picture_or_drawing.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 160, 131, 20))
        self.label_4.setObjectName("label_4")
        self.method = QtWidgets.QComboBox(self.centralwidget)
        self.method.setGeometry(QtCore.QRect(80, 220, 171, 31))
        self.method.setObjectName("method")
        self.method.addItem("")
        self.method.addItem("")
        self.random_selection = QtWidgets.QPushButton(self.centralwidget)
        self.random_selection.setGeometry(QtCore.QRect(78, 274, 171, 31))
        self.random_selection.setObjectName("random_selection")
        self.clear_table = QtWidgets.QPushButton(self.centralwidget)
        self.clear_table.setGeometry(QtCore.QRect(80, 320, 171, 31))
        self.clear_table.setObjectName("clear_table")
        self.re = QtWidgets.QPushButton(self.centralwidget)
        self.re.setGeometry(QtCore.QRect(80, 450, 171, 31))
        self.re.setObjectName("re")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(640, 180, 221, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.dArea_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.dArea_Layout.setContentsMargins(0, 0, 0, 0)
        self.dArea_Layout.setSpacing(0)
        self.dArea_Layout.setObjectName("dArea_Layout")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(290, 200, 91, 51))
        self.result.setObjectName("result")
        self.knnResult = QtWidgets.QLabel(self.centralwidget)
        self.knnResult.setGeometry(QtCore.QRect(430, 230, 91, 131))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.knnResult.setFont(font)
        self.knnResult.setObjectName("knnResult")
        self.k = QtWidgets.QSlider(self.centralwidget)
        self.k.setGeometry(QtCore.QRect(80, 410, 221, 16))
        self.k.setOrientation(QtCore.Qt.Horizontal)
        self.k.setObjectName("k")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 370, 131, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 370, 31, 17))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.k.valueChanged['int'].connect(self.label_2.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picture_or_drawing.setItemText(0, _translate("MainWindow", "1:  MNIST random selection"))
        self.label_4.setText(_translate("MainWindow", "Data Input area"))
        self.method.setItemText(0, _translate("MainWindow", "D22"))
        self.method.setItemText(1, _translate("MainWindow", "D23"))
        self.random_selection.setText(_translate("MainWindow", "Random Selection"))
        self.clear_table.setText(_translate("MainWindow", "Clear"))
        self.re.setText(_translate("MainWindow", "Recognization"))
        self.result.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Result : </span></p></body></html>"))
        self.knnResult.setText(_translate("MainWindow", "9"))
        self.label.setText(_translate("MainWindow", "K - neighbors:"))
        self.label_2.setText(_translate("MainWindow", "1"))
